### ISSUE TITLE
[Feature Requests] please allow using FQDN at PublicIP

### ISSUE THREAD

**Issue by Maximilian2022** [Impostor/Impostor.Http#4]
Hi.
This is a feature request.
please consider.

In config.json, I used my server's fqdn at PublicIP instead of ip address.
it is because i'm running on free cloud, so ip address may change.

would you please allow using FQDN at PublicIP in config.json?
currently, when I use fqdn instead of ip, imposter.http crashes with error.

[14:42:28 ERR] Connection id "0HMLUEB5OQOPE", Request id "0HMLUEB5OQOPE:00000003": An unhandled exception was thrown by the application.
System.FormatException: An invalid IP address was specified.
 ---> System.Net.Sockets.SocketException (22): Invalid argument
   --- End of inner exception stack trace ---
   at System.Net.IPAddressParser.Parse(ReadOnlySpan`1 ipSpan, Boolean tryParse)
   at System.Net.IPAddress.Parse(String ipString)
   at Impostor.Http.GamesController..ctor(IGameManager gameManager, ListingManager listingManager, IOptions`1 serverConfig)
   at lambda_method6(Closure , IServiceProvider , Object[] )
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerActivatorProvider.<>c__DisplayClass7_0.<CreateActivator>b__0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerFactoryProvider.<>c__DisplayClass6_0.<CreateControllerFactory>g__CreateController|0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)

Thank you.

**Comment by miniduikboot** [comment]
Hi there,

Impostor(.Http) need to know the public ip address of the server to send people to that server. We need to send this IPv4 address to the client, so currently we ask users to just fill in the IP, but we could autodetect it.

If I may ask, how often does your public IP change? To phrase it differently: does that happen on boot or also while Impostor is running?

**Comment by Maximilian2022** [comment]
hi, thanks for your quick reply.

i use GCP, and my GCP server is running when match is making on my discord server.
so everytime i boot up for Amongus, ip address may different.

Thank you.

**Comment by miniduikboot** [comment]
The PR I just merged should allow you to specify an FQDN as your public ip address. Let me know if this works for you.

**Comment by Maximilian2022** [comment]
Hi.

Thanks for your quick & nice work!

I test with latest nightly build and it works in my environment.

Thank you.
